version: '3.8'

services:
  django:
    build:
      context: ../../
      dockerfile: infrastructure/docker/django/Dockerfile.dev
    container_name: scaleup_django_dev
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    networks:
      - scaleup_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: scaleup_mailhog_dev
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - scaleup_network